image: nexus.spaceapplications.com/repository/infuse/cdff-ci:1.6.5.2

stages:
  - platform
  - autogeneration
  - build
  - test
  - deploy

hardware:
  stage : platform
  script:
      - cat /proc/cpuinfo
      - lscpu
      
autogeneration:
  stage : autogeneration
  script:
      - cd Tools/ASNtoC
      - ./GeneratorScript.sh
  artifacts:
    paths:
      - Common/Types/C/

build:
  stage: build
  script:
      - pwd
      - cp -rf /CDFF/External/install ./External/install
      - mkdir build
      - cd build
      - cmake -DCMAKE_INSTALL_PREFIX=./ ..
      - make
  artifacts:
    paths:
      - build/

cmake test:
  stage: test
  script:
      - cd build
      - make test

individual test:
  stage: test
  script:
      - cd build/Tests/UnitTests
      - ./ParametersHelperTest
      - ./HarrisDetector2DTest
      - ./OrbDetectorDescriptorTest
      - ./FundamentalMatrixRansacTest
      - ./EssentialMatrixRansacTest
      - ./FlannMatcherTest
      - ./TriangulationTest
      - ./HarrisDetector3DTest 
      - ./ShotDescriptor3DTest
      - ./Ransac3DTest
      - ./Icp3DTest
      - ./MatFrameConvertersTest
      - ./MatVisualPointFeatureVector2DConvertersTest
      - ./MatVisualPointFeatureVector3DConvertersTest
      - ./PointCloudPclPointCloudConvertersTest
      - ./PointCloudPclNormalsCloudConvertersTest
      - ./VisualPointFeatureVector3DPclPointCloudConvertersTest
      - ./Transform3DEigenTransformConvertersTest
      
deploy_staging:
  stage: deploy
  script:
  - echo "Deploy to staging server"
  only:
  - master
