image: nexus.spaceapplications.com/repository/infuse/infuse:1.6.3

stages:
  - autogeneration
  - build
  - test
  - deploy

dependencies:
  stage : dependencies
  script:
      - cp -rf /CDFF/External ./External
  artifacts:
    paths:
      - External/

autogeneration:
  stage : autogeneration
  script:
      - cd Tools/ASNtoC
      - ./GeneratorScript.sh
  artifacts:
    paths:
      - Common/Types/C/

build:
  stage: build
  script:
      - mkdir build
      - cd build
      - cmake -DCMAKE_INSTALL_PREFIX=./ ..
      - make
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
      - cd build
      - make test

deploy_staging:
  stage: deploy
  script:
  - echo "Deploy to staging server"
  only:
  - master
