image: nexus.spaceapplications.com/repository/infuse/cdff-ci:1.7

stages:
  - platform
  - autogeneration
  - build
  - test
  - deploy

hardware:
  stage : platform
  script:
      - cat /proc/cpuinfo
      - lscpu

autogeneration:
  stage : autogeneration
  script:
      - cd Tools/ASNtoC
      - ./GeneratorScript.sh
  artifacts:
    paths:
      - Common/Types/C/
    expire_in: 4 weeks

build:
  stage: build
  script:
      - pwd
      - mkdir build
      - cd build
      - cmake -DCMAKE_INSTALL_PREFIX=./ ..
      - make
  artifacts:
    paths:
      - build/
    expire_in: 4 weeks

cmake test:
  stage: test
  script:
      - cd build
      - make test

deploy_staging:
  stage: deploy
  script:
      - echo "Deploy to staging server"
  only:
      - master
