/* --------------------------------------------------------------------------
*
* (C) Copyright …
*
* ---------------------------------------------------------------------------
*/

/*!
 * @file VisualPointFeatureVector3D.asn
 * @date 01/12/2017
 * @author Alessandro Bianco
 */

/*!
 * @addtogroup BaseTypes
 * 
 * Specification of the VisualPointFeatureVector3D class.
 * 
 * 
 * @{
 */
VisualPointFeature3DNS DEFINITIONS ::=
BEGIN

IMPORTS
Point3D FROM GeometryNS;

VisualPointFeature3D ::= SEQUENCE
	{
	point		Point3D,
	descriptor	SEQUENCE OF REAL
	}

VisualPointFeatureVector3D ::= SEQUENCE OF VisualPointFeature3D

END

/** @} */
