/* --------------------------------------------------------------------------
*
* (C) Copyright …
*
* ---------------------------------------------------------------------------
*/

/*!
 * @file Sequences.asn
 * @date 04/06/2018
 * @author Alessandro Bianco
 */

/*!
 * @addtogroup BaseTypes
 * 
 * Specification of the Sequence of other base types class.
 * 
 * 
 * @{
 */
SequencesNS DEFINITIONS ::=
BEGIN

IMPORTS
Point2D FROM GeometryNS
T-Int32, T-UInt32, T-Int8, T-UInt8, T-Boolean  FROM TASTE-BasicTypes 
T-Int64, T-UInt16, T-Double, T-Float, T-UInt64, T-String FROM TASTE-ExtendedTypes
Frame FROM Frame-Types
Pose FROM Pose-Types;

-- Max. name size
maxFramesSequenceLength T-UInt32 ::= 10
maxPosesSequenceLength T-UInt32 ::= 10

FramesSequence ::= SEQUENCE (SIZE(0..maxFramesSequenceLength)) OF Frame

PosesSequence ::= SEQUENCE (SIZE(0..maxPosesSequenceLength)) OF Pose

END
