FROM nexus.spaceapplications.com/repository/infuse/cdff-ci:latest

RUN apt-get update && apt-get install -y \
  python3 \
  python3-dev \
  python3-pip \
  autoconf \
  automake \
  freeglut3-dev \
  graphviz \
  graphviz-dev \
  libgoogle-glog-dev \
  libjsoncpp-dev \
  libopenscenegraph-dev \
  libpoco-dev \
  libproj-dev \
  libqt4-dev \
  libqt4-opengl-dev \
  libtinyxml-dev \
  qt4-qmake \
  pkg-config \
  ruby \
  ruby-dev \
  sudo \
  python3-pyqt4 \
  libgdal-dev \
  libproj-dev \
  python3-gdal
RUN pip3 install --upgrade pip
RUN pip3 install pyyaml jinja2 cython numpy msgpack-python pydot nose nose2 pandas memory_profiler coverage

RUN mkdir -p -m 700 /root/.ssh/ && \
  ssh-keyscan gitlab.spaceapplications.com >> /root/.ssh/known_hosts

# Prepare non-interactive autoproj setup with CI user
WORKDIR /tmp/infuse
RUN wget http://www.rock-robotics.org/autoproj_bootstrap --directory-prefix=/tmp/infuse/
COPY dev-ci/config.yml /tmp/
RUN AUTOPROJ_BOOTSTRAP_IGNORE_NONEMPTY_DIR=1 ruby autoproj_bootstrap git https://cdff-dev:cdff-dev@gitlab.spaceapplications.com/InFuse/cdff-buildconf.git branch=cdff_dev --seed-config=/tmp/config.yml
COPY dev-ci/00_ci_user.yml /tmp/infuse/autoproj/overrides.d/
COPY dev-ci/manifest /tmp/infuse/autoproj/

# Autoproj needs these to be defined (will be removed later):
RUN git config --global user.email infuse@example.com \
  && git config --global user.name InFuse

SHELL ["/bin/bash", "-c"]

RUN source env.sh && autoproj update
RUN mkdir -p /tmp/infuse/install/share/cmake

# We use CDFF's preinstalled dependencies.
RUN echo "Autobuild::Package['cdff/CDFF'].define 'USE_BUNDLED_DEPENDENCIES', 'OFF'" >> autoproj/overrides.rb

# Fix missing pkg-config files
COPY dev-ci/pcl_registration-1.8.pc dev-ci/pcl_features-1.8.pc dev-ci/pcl_2d-1.8.pc /tmp/infuse/install/lib/pkgconfig/

# Install direct dependencies of CDFF_dev
RUN source env.sh && autoproj build \
  && rm -rf /tmp/infuse/cdff/CDFF/.git \
  && rm -rf /tmp/infuse/autoproj \
  && rm -rf /tmp/infuse/base \
  && rm -rf /tmp/infuse/control \
  && rm -rf /tmp/infuse/envire \
  && rm -rf /tmp/infuse/esrocos \
  && rm -rf /tmp/infuse/external \
  && rm -rf /tmp/infuse/gui \
  && rm -rf /tmp/infuse/infuse \
  && rm -rf /tmp/infuse/simulation \
  && rm -rf /tmp/infuse/tools \
  && rm /tmp/infuse/autoproj_bootstrap

# Reset git configuration
RUN rm /root/.gitconfig

WORKDIR /
ARG VERSION="2.2.6"
ARG SHA=0000
ENV IMAGE_VERSION=$VERSION
ENV IMAGE_SHA=$SHA
LABEL version=${IMAGE_VERSION}
LABEL maintainer="Alexander.Fabisch@dfki.de"
LABEL description="Image providing the dependencies of CDFF-dev for continuous integration"
